app/models.py
from . import db,login_manager
from werkzeug.security import  generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime
import os

app/main/forms.py
from  flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators=[Required()])
    submit = SubmitField('Submit')

class PitchingForm(FlaskForm):
    description = TextAreaField('Give a pitch',validators=[Required()])
    category = SelectField('Category', choices=[('Technology','Technology'),('Sports','Sports'),('Religion','Religion')])
    submit = SubmitField('Pitch!')

class CommentForm(FlaskForm):
    details = StringField('Write a comment',validators=[Required()])
    submit = SubmitField('Comment')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet,configure_uploads,IMAGES
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'



db = SQLAlchemy()
bootstrap = Bootstrap()
photos = UploadSet('photos',IMAGES)


def create_app(config_name):
    # Initializing Application
    app = Flask(__name__)

    #Initializing Flask Extensions
    login_manager.init_app(app)


    bootstrap.init_app(app)

    # Setting up configuration
    app.config.from_object(config_options[config_name])
    config_options[config_name].__init__(app)

    # Registering main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Registering auth blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # CONFIGURE UPLOADSET
    configure_uploads(app,photos)



    db.init_app(app)





    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,redirect,url_for,abort,request
from . import main
from flask_login import login_required,current_user
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,PitchingForm,CommentForm
from .. import db,photos


@main.route('/', methods = ['GET','POST'])
def index():
    religion = Pitch.query.filter_by(category='Religion').all()
    sports = Pitch.query.filter_by(category='Sports').all()
    tech = Pitch.query.filter_by(category='Technology').all()

    return render_template('index.html', tech = tech,sports = sports,religion= religion)



@main.route('/sports', methods = ['GET','POST'])
def sports():
    sports = Pitch.query.filter_by(category = 'Sports').all()
    print(sports)


    return render_template('sports.html',sports = sports)

@main.route('/religion')
def religion():
    religion = Pitch.query.filter_by(category = 'Religion').all()
    print(religion)

    return render_template('religion.html',religion= religion)

@main.route('/post', methods = ['GET','POST'])
@login_required
def new_post():
   form = PitchingForm()
   if form.validate_on_submit():
       description = form.description.data
       category = form.category.data
       user = current_user


       new_pitch = Pitch(description = description,category = category,user = user)

       # save pitch
       db.session.add(new_pitch)
       db.session.commit()

       return redirect(url_for('main.index',uname = user.username))

   return render_template('post.html',form = form)

@main.route('/comments/<int:id>', methods = ['GET','POST'])
@login_required
def new_comment(id):
    form_comment = CommentForm()

    comment = Comment.query.filter_by(pitch_id=id).all()

    if form_comment.validate_on_submit():
        details = form_comment.details.data
        user = current_user
        print(comment)
        new_comment = Comment(details = details,user =user,pitch_id=id)
        # # save comment
        db.session.add(new_comment)
        db.session.commit()



        return redirect(url_for('main.index', uname = user.username))
    return render_template('comments.html',form_comment = form_comment,comment=comment)

# @main.route('/post/up_vote/<int:id>')
# @login_required
# def up_vote(id):
#         post = Pitch.query.filter_by(id=id).first()
#         post.up_vote = post.up_vote +1
#         db.session.add(post)
#         db.session.commit()
#
#         return redirect(url_for('main.index'))


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:

        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname = user.username))

    return render_template('profile/update.html',form =form)




@main.route('/user/<uname>/update/pic',methods =['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()

    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block  -->
{% block navbar %}

    {% include 'navbar.html' %}

{% endblock %}

app/templates/comments.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<br><br><br><br><br>
<center>

<div class="col-md-12">

  {{wtf.quick_form(form_comment)}}

    {% for c in comment%}
<div class="prof">
<div class="col-lg-3">

        <div class="panel panel-info">
    <div class="panel-heading">
    <h1 class="panel-title">Comments</h1>

</div>

    <div class="panel-body">
<h1><p>"{{c.details}}"</p></h1>
    </div>
<p>Posted by {{c.user.username}}</p>
    <div class="panel-footer">
<p><a href="/comments">Comment</a> </p>
    </div>
        </div>
</div>
</div>


{% endfor %}

</div>
</center>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<br><br><br><br>
<div class="container">
    <div class="row">
        {% for r in religion%}
<div class="col-md-4">

      <div class="panel panel-info">
    <div class="panel-heading">
    <h1 class="panel-title">Religion</h1>

</div>

    <div class="panel-body">
<p>"{{r.description}}"</p>
    </div>
<p class="foot">Posted by {{r.user.username}}</p>
    <div class="panel-footer">
<p><a href="/comments/{{r.id}}">Comment</a></p>

        <i class="fa fa-thumbs-up fa-2x"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-thumbs-down fa-2x"></i>
    </div>
        </div>

</div>
        {% endfor %}
{% for t in tech%}
        <div class="col-md-4">

      <div class="panel panel-info">
    <div class="panel-heading">
    <h1 class="panel-title">Technology</h1>

</div>

    <div class="panel-body">
<p>"{{t.description}}"</p>
    </div>
<p class="foot">Posted by {{t.user.username}}</p>
    <div class="panel-footer">
<p><a href="/comments/{{t.id}}">Comment</a></p>
    </div>
        </div>

</div>
{% endfor %}
{% for s in sports%}
        <div class="col-md-4">

    <div class="panel panel-info">
    <div class="panel-heading">
    <h1 class="panel-title">Sports</h1>

</div>

    <div class="panel-body">
<p>"{{s.description}}"</p>
    </div>
        <p>Posted by {{s.user.username}}</p>
    <div class="panel-footer">
<p><a href="/comments/{{s.id}}">Comment</a></p>
    </div>
        </div>

</div>
{% endfor %}

</div>
</div>



{% endblock%}

<!--#https://www.codewars.com/kata/find-the-divisors/train/python-->

app/templates/navbar.html
{% extends 'base.html'%}

{% block styles%}
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
<link rel="stylesheet" href="{{url_for('static',filename='css/font-awesome.min.css')}}">
{% endblock %}

{% block navbar %}
<body>
<div class="topnav">
    <a href="/">Home</a>
    <a href="/religion">Religion</a>
     <a href="/sports">Sports</a>
    <a href="/technology">Technology</a>
    {% if current_user.is_authenticated %}
    <a href="/post">Post</a>
    <a href="{{url_for('auth.logout')}}" class="sign">Sign out</a>
    {% else %}
    <a href="{{url_for('auth.login')}}" class="sign">Sign In</a>
    <a href="{{url_for('auth.register')}}" class="sign">Sign Up</a>
    {%endif%}
    <a  href="{{url_for('main.profile',uname=current_user.username)}}" id="user">{{current_user.username}}</a>


</div>

</body>

{% endblock %}

app/templates/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<br><br><br><br><br><br><br><br>
{{wtf.quick_form(form)}}
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}


{% block content %}
<br xmlns="http://www.w3.org/1999/html"><br><br><br><br><br>
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <div class="prof">
                <center>
            {% if user.profile_pic %}
            <img src="{{url_for('static',filename=user.profile_pic)}}" alt="pic" class="img-thumbnail" style="border-radius: 50%;width: 300px;height: 300px">
                </center>
            {% else %}
            <p>No profile pic</p>
            {% endif %}

                <h3><p>{{user.username| capitalize}}</p></h3>
                <h2><p>{{user.email}}</p></h2>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p>{{user.bio}}</p>
            {% else %}
            <p>{{user.username| capitalize}} has no bio</p>
            {% endif %}

            </div>


        </div>

<!--Display profile photo-->
        <div class="col-md-4">


            {% if user == current_user %}

            <form action="{{url_for('main.update_pic',uname = user.username)}}" method ="post" enctype ="multipart/form-data">
                <input type="file" name="photo" class="form-control" required>
                <input type="submit"><br><br>

                <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}




        </div>





    </div>





</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<br><br><br><br>
{{wtf.quick_form(form)}}
{% endblock %}

app/templates/religion.html
{% extends 'base.html' %}
<div class="container" id="container">
    <div class="row">
{% block content %}
<br><br><br><br>
{% for r in religion%}

<div class="col-lg-3">

        <div class="panel panel-info">
    <div class="panel-heading">
    <h1 class="panel-title">Religion</h1>

</div>

    <div class="panel-body">
<p>"{{r.description}}"</p>
    </div>
<p>Posted by {{r.user.username}}</p>
    <div class="panel-footer">
<p><a href="/comments/{{r.id}}">Comment</a></p>
    </div>
        </div>
</div>



{% endfor %}

{% endblock%}
           </div>
</div>

app/templates/sports.html
{% extends 'base.html' %}
<div class="container">
    <div class="row">
{% block content %}
<br><br><br><br>
{% for s in sports%}

<div class="col-md-3">



        <div class="panel panel-info">
    <div class="panel-heading">
    <h2 class="panel-title">Sports</h2>

</div>

    <div class="panel-body">
<p>"{{s.description}}"</p>
    </div>
<p>Posted by {{s.user.username}}</p>
    <div class="panel-footer">
<p><a href="/comments/{{s.id}}">Comment</a></p>
    </div>
        </div>
</div>



{% endfor %}


{% endblock%}
          </div>
</div>